LastSessions<|||>1<|||>graduation_project_clacet2
LastActiveSession<|||>1<|||>graduation_project_clacet2
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
ColWidths_frmTableEditor.listColumns<|||>1<|||>40,100,152,90,60,65,50,117,130,139,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>234,100,80,120,80
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>200,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,420
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,316
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,316,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,188
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,256
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
MainWinWidth<|||>3<|||>879
MainWinHeight<|||>3<|||>466
sqloutheight<|||>3<|||>34
MainWinMaximized<|||>3<|||>1
querymemoheight<|||>3<|||>412
dbtreewidth<|||>3<|||>391
FontSize<|||>3<|||>8
FileDialogEncoding_MainForm<|||>3<|||>0
SQLFile0<|||>1<|||>C:\laragon\bin\heidisql\Backups\query-tab-2026-05-01_18-21-36-233.sql
SQLFile1<|||>1<|||>C:\laragon\bin\heidisql\Backups\query-tab-2026-04-06_23-33-24-874.sql
ExportSQL_CreateDatabases<|||>3<|||>0
ExportSQL_CreateTables<|||>3<|||>0
ExportSQL_Filenames<|||>1<|||>C:\Uni\Assiments\MetroDB.sql<{{{><}}}>MetroDB<{{{><}}}>
Servers\Ass_web\SessionCreated<|||>1<|||>2026-05-01 18:17:13
Servers\Ass_web\Host<|||>1<|||>127.0.0.1
Servers\Ass_web\WindowsAuth<|||>3<|||>0
Servers\Ass_web\CleartextPluginEnabled<|||>3<|||>0
Servers\Ass_web\User<|||>1<|||>root
Servers\Ass_web\Password<|||>1<|||>4
Servers\Ass_web\LoginPrompt<|||>3<|||>0
Servers\Ass_web\Port<|||>1<|||>3306
Servers\Ass_web\NetType<|||>3<|||>0
Servers\Ass_web\Compressed<|||>3<|||>0
Servers\Ass_web\LocalTimeZone<|||>3<|||>0
Servers\Ass_web\QueryTimeout<|||>3<|||>30
Servers\Ass_web\KeepAlive<|||>3<|||>20
Servers\Ass_web\FullTableStatus<|||>3<|||>1
Servers\Ass_web\Databases<|||>1<|||>
Servers\Ass_web\Library<|||>1<|||>libmariadb.dll
Servers\Ass_web\Comment<|||>1<|||>
Servers\Ass_web\StartupScriptFilename<|||>1<|||>
Servers\Ass_web\TreeBackground<|||>3<|||>536870911
Servers\Ass_web\SSHtunnelActive<|||>3<|||>0
Servers\Ass_web\SshExecutable<|||>1<|||>
Servers\Ass_web\SSHtunnelHost<|||>1<|||>
Servers\Ass_web\SSHtunnelHostPort<|||>3<|||>22
Servers\Ass_web\SSHtunnelUser<|||>1<|||>
Servers\Ass_web\SSHtunnelPassword<|||>1<|||>9
Servers\Ass_web\SSHtunnelTimeout<|||>3<|||>4
Servers\Ass_web\SSHtunnelPrivateKey<|||>1<|||>
Servers\Ass_web\SSHtunnelPort<|||>3<|||>3307
Servers\Ass_web\SSL_Active<|||>3<|||>0
Servers\Ass_web\SSL_Key<|||>1<|||>
Servers\Ass_web\SSL_Cert<|||>1<|||>
Servers\Ass_web\SSL_CA<|||>1<|||>
Servers\Ass_web\SSL_Cipher<|||>1<|||>
Servers\Ass_web\SSL_Verification<|||>3<|||>2
Servers\Ass_web\IgnoreDatabasePattern<|||>1<|||>
Servers\Ass_web\LogFileDdl<|||>3<|||>0
Servers\Ass_web\LogFileDml<|||>3<|||>0
Servers\Ass_web\LogFilePath<|||>1<|||>C:\Users\FATMA-HASANIN\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Ass_web\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\Ass_web\ConnectCount<|||>3<|||>1
Servers\Ass_web\ServerVersion<|||>3<|||>80403
Servers\Ass_web\LastConnect<|||>1<|||>2026-05-01 18:17:24
Servers\Ass_web\lastUsedDB<|||>1<|||>student_db
Servers\Ass_web\QueryHistory\2<|||>1<|||>2026-05-01 18:21:40|Task_1|31|-- ============================================================<{{{><}}}>-- File:    database.sql<{{{><}}}>-- Purpose: Database initialisation script for the Student<{{{><}}}>--          Management System. Import this file via phpMyAdmin<{{{><}}}>--          (or the MySQL CLI) to create the database, tables,<{{{><}}}>--          and a default admin account in one step.<{{{><}}}>-- Author:  Student Management System<{{{><}}}>-- ============================================================<{{{><}}}><{{{><}}}>-- [SERVER-SIDE] Create the database if it does not already exist<{{{><}}}>CREATE DATABASE IF NOT EXISTS student_db;<{{{><}}}><{{{><}}}>-- [SERVER-SIDE] Switch to the newly created (or existing) database<{{{><}}}>USE student_db;<{{{><}}}><{{{><}}}>-- ============================================================<{{{><}}}>-- Table: students<{{{><}}}>-- Stores registered student accounts.<{{{><}}}>-- ============================================================<{{{><}}}>CREATE TABLE IF NOT EXISTS students (<{{{><}}}>    id         INT          NOT NULL AUTO_INCREMENT,<{{{><}}}>    name       VARCHAR(100) NOT NULL,<{{{><}}}>    email      VARCHAR(150) NOT NULL,<{{{><}}}>    password   VARCHAR(255) NOT NULL,   -- bcrypt hash via password_hash()<{{{><}}}>    age        INT          NOT NULL,<{{{><}}}>    course     VARCHAR(100) NOT NULL,<{{{><}}}>    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,<{{{><}}}>    PRIMARY KEY (id),<{{{><}}}>    UNIQUE KEY uq_students_email (email)<{{{><}}}>) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;<{{{><}}}><{{{><}}}>-- ============================================================<{{{><}}}>-- Table: admins<{{{><}}}>-- Stores administrator accounts (separate from students).<{{{><}}}>-- ============================================================<{{{><}}}>CREATE TABLE IF NOT EXISTS admins (<{{{><}}}>    id       INT          NOT NULL AUTO_INCREMENT,<{{{><}}}>    email    VARCHAR(150) NOT NULL,<{{{><}}}>    password VARCHAR(255) NOT NULL,   -- bcrypt hash via password_hash()<{{{><}}}>    PRIMARY KEY (id),<{{{><}}}>    UNIQUE KEY uq_admins_email (email)<{{{><}}}>) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;<{{{><}}}><{{{><}}}>-- ============================================================<{{{><}}}>-- Default admin account<{{{><}}}>-- Email   : admin@sms.com<{{{><}}}>-- Password: admin123<{{{><}}}>-- The hash below is the bcrypt (PASSWORD_BCRYPT) hash of<{{{><}}}>-- "admin123" generated with PHP's password_hash().<{{{><}}}>-- ============================================================<{{{><}}}>INSERT INTO admins (email, password)<{{{><}}}>SELECT 'admin@sms.com',<{{{><}}}>       '$2y$10$TKh8H1.PfbuNILze3BphmulkTssRlFpuv1HKPsJxX0b2tZnIqIyWm'<{{{><}}}>WHERE NOT EXISTS (<{{{><}}}>    SELECT 1 FROM admins WHERE email = 'admin@sms.com'<{{{><}}}>);<{{{><}}}>
Servers\graduation_project_clacet2\SessionCreated<|||>1<|||>2026-04-06 23:34:53
Servers\graduation_project_clacet2\Host<|||>1<|||>127.0.0.1
Servers\graduation_project_clacet2\WindowsAuth<|||>3<|||>0
Servers\graduation_project_clacet2\CleartextPluginEnabled<|||>3<|||>0
Servers\graduation_project_clacet2\User<|||>1<|||>root
Servers\graduation_project_clacet2\Password<|||>1<|||>5
Servers\graduation_project_clacet2\LoginPrompt<|||>3<|||>0
Servers\graduation_project_clacet2\Port<|||>1<|||>3306
Servers\graduation_project_clacet2\NetType<|||>3<|||>0
Servers\graduation_project_clacet2\Compressed<|||>3<|||>0
Servers\graduation_project_clacet2\LocalTimeZone<|||>3<|||>0
Servers\graduation_project_clacet2\QueryTimeout<|||>3<|||>30
Servers\graduation_project_clacet2\KeepAlive<|||>3<|||>20
Servers\graduation_project_clacet2\FullTableStatus<|||>3<|||>1
Servers\graduation_project_clacet2\Databases<|||>1<|||>graduation_project_clacet2
Servers\graduation_project_clacet2\Library<|||>1<|||>libmariadb.dll
Servers\graduation_project_clacet2\Comment<|||>1<|||>
Servers\graduation_project_clacet2\StartupScriptFilename<|||>1<|||>
Servers\graduation_project_clacet2\TreeBackground<|||>3<|||>536870911
Servers\graduation_project_clacet2\SSHtunnelActive<|||>3<|||>0
Servers\graduation_project_clacet2\SshExecutable<|||>1<|||>
Servers\graduation_project_clacet2\SSHtunnelHost<|||>1<|||>
Servers\graduation_project_clacet2\SSHtunnelHostPort<|||>3<|||>22
Servers\graduation_project_clacet2\SSHtunnelUser<|||>1<|||>
Servers\graduation_project_clacet2\SSHtunnelPassword<|||>1<|||>7
Servers\graduation_project_clacet2\SSHtunnelTimeout<|||>3<|||>4
Servers\graduation_project_clacet2\SSHtunnelPrivateKey<|||>1<|||>
Servers\graduation_project_clacet2\SSHtunnelPort<|||>3<|||>3307
Servers\graduation_project_clacet2\SSL_Active<|||>3<|||>0
Servers\graduation_project_clacet2\SSL_Key<|||>1<|||>
Servers\graduation_project_clacet2\SSL_Cert<|||>1<|||>
Servers\graduation_project_clacet2\SSL_CA<|||>1<|||>
Servers\graduation_project_clacet2\SSL_Cipher<|||>1<|||>
Servers\graduation_project_clacet2\SSL_Verification<|||>3<|||>2
Servers\graduation_project_clacet2\IgnoreDatabasePattern<|||>1<|||>
Servers\graduation_project_clacet2\LogFileDdl<|||>3<|||>0
Servers\graduation_project_clacet2\LogFileDml<|||>3<|||>0
Servers\graduation_project_clacet2\LogFilePath<|||>1<|||>C:\Users\FATMA-HASANIN\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\graduation_project_clacet2\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\graduation_project_clacet2\ConnectCount<|||>3<|||>12
Servers\graduation_project_clacet2\ServerVersion<|||>3<|||>80403
Servers\graduation_project_clacet2\LastConnect<|||>1<|||>2026-05-21 18:31:52
Servers\graduation_project_clacet2\lastUsedDB<|||>1<|||>graduation_project_clacet2
Servers\Laragon.MySQL\SessionCreated<|||>1<|||>2024-12-16 22:28:25
Servers\Laragon.MySQL\Host<|||>1<|||>127.0.0.1
Servers\Laragon.MySQL\WindowsAuth<|||>3<|||>0
Servers\Laragon.MySQL\CleartextPluginEnabled<|||>3<|||>0
Servers\Laragon.MySQL\User<|||>1<|||>root
Servers\Laragon.MySQL\Password<|||>1<|||>2
Servers\Laragon.MySQL\LoginPrompt<|||>3<|||>0
Servers\Laragon.MySQL\Port<|||>1<|||>3306
Servers\Laragon.MySQL\NetType<|||>3<|||>0
Servers\Laragon.MySQL\Compressed<|||>3<|||>0
Servers\Laragon.MySQL\LocalTimeZone<|||>3<|||>0
Servers\Laragon.MySQL\QueryTimeout<|||>3<|||>30
Servers\Laragon.MySQL\KeepAlive<|||>3<|||>20
Servers\Laragon.MySQL\FullTableStatus<|||>3<|||>1
Servers\Laragon.MySQL\Databases<|||>1<|||>
Servers\Laragon.MySQL\Library<|||>1<|||>libmariadb.dll
Servers\Laragon.MySQL\Comment<|||>1<|||>
Servers\Laragon.MySQL\StartupScriptFilename<|||>1<|||>
Servers\Laragon.MySQL\TreeBackground<|||>3<|||>536870911
Servers\Laragon.MySQL\SSHtunnelActive<|||>3<|||>0
Servers\Laragon.MySQL\SshExecutable<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelHost<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelHostPort<|||>3<|||>22
Servers\Laragon.MySQL\SSHtunnelUser<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPassword<|||>1<|||>8
Servers\Laragon.MySQL\SSHtunnelTimeout<|||>3<|||>4
Servers\Laragon.MySQL\SSHtunnelPrivateKey<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPort<|||>3<|||>3307
Servers\Laragon.MySQL\SSL_Active<|||>3<|||>0
Servers\Laragon.MySQL\SSL_Key<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cert<|||>1<|||>
Servers\Laragon.MySQL\SSL_CA<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cipher<|||>1<|||>
Servers\Laragon.MySQL\SSL_Verification<|||>3<|||>2
Servers\Laragon.MySQL\IgnoreDatabasePattern<|||>1<|||>
Servers\Laragon.MySQL\LogFileDdl<|||>3<|||>0
Servers\Laragon.MySQL\LogFileDml<|||>3<|||>0
Servers\Laragon.MySQL\LogFilePath<|||>1<|||>C:\Users\Leo\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Laragon.MySQL\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\Laragon.MySQL\ConnectCount<|||>3<|||>2
Servers\Laragon.MySQL\ServerVersion<|||>3<|||>80403
Servers\Laragon.MySQL\LastConnect<|||>1<|||>2026-04-06 17:15:44
Servers\Laragon.MySQL\lastUsedDB<|||>1<|||>mysql
Servers\Metro_DB\SessionCreated<|||>1<|||>2026-05-03 23:06:11
Servers\Metro_DB\Host<|||>1<|||>127.0.0.1
Servers\Metro_DB\WindowsAuth<|||>3<|||>0
Servers\Metro_DB\CleartextPluginEnabled<|||>3<|||>0
Servers\Metro_DB\User<|||>1<|||>root
Servers\Metro_DB\Password<|||>1<|||>5
Servers\Metro_DB\LoginPrompt<|||>3<|||>0
Servers\Metro_DB\Port<|||>1<|||>3306
Servers\Metro_DB\NetType<|||>3<|||>0
Servers\Metro_DB\Compressed<|||>3<|||>0
Servers\Metro_DB\LocalTimeZone<|||>3<|||>0
Servers\Metro_DB\QueryTimeout<|||>3<|||>30
Servers\Metro_DB\KeepAlive<|||>3<|||>20
Servers\Metro_DB\FullTableStatus<|||>3<|||>1
Servers\Metro_DB\Databases<|||>1<|||>
Servers\Metro_DB\Library<|||>1<|||>libmariadb.dll
Servers\Metro_DB\Comment<|||>1<|||>
Servers\Metro_DB\StartupScriptFilename<|||>1<|||>
Servers\Metro_DB\TreeBackground<|||>3<|||>536870911
Servers\Metro_DB\SSHtunnelActive<|||>3<|||>0
Servers\Metro_DB\SshExecutable<|||>1<|||>
Servers\Metro_DB\SSHtunnelHost<|||>1<|||>
Servers\Metro_DB\SSHtunnelHostPort<|||>3<|||>22
Servers\Metro_DB\SSHtunnelUser<|||>1<|||>
Servers\Metro_DB\SSHtunnelPassword<|||>1<|||>8
Servers\Metro_DB\SSHtunnelTimeout<|||>3<|||>4
Servers\Metro_DB\SSHtunnelPrivateKey<|||>1<|||>
Servers\Metro_DB\SSHtunnelPort<|||>3<|||>3307
Servers\Metro_DB\SSL_Active<|||>3<|||>0
Servers\Metro_DB\SSL_Key<|||>1<|||>
Servers\Metro_DB\SSL_Cert<|||>1<|||>
Servers\Metro_DB\SSL_CA<|||>1<|||>
Servers\Metro_DB\SSL_Cipher<|||>1<|||>
Servers\Metro_DB\SSL_Verification<|||>3<|||>2
Servers\Metro_DB\IgnoreDatabasePattern<|||>1<|||>
Servers\Metro_DB\LogFileDdl<|||>3<|||>0
Servers\Metro_DB\LogFileDml<|||>3<|||>0
Servers\Metro_DB\LogFilePath<|||>1<|||>C:\Users\FATMA-HASANIN\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Metro_DB\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\Metro_DB\ConnectCount<|||>3<|||>1
Servers\Metro_DB\ServerVersion<|||>3<|||>80403
Servers\Metro_DB\LastConnect<|||>1<|||>2026-05-03 23:06:27
Servers\Metro_DB\QueryHistory\1<|||>1<|||>2026-05-03 23:09:20|MetroDB|15|USE MetroDB;<{{{><}}}>INSERT INTO `Lines` (`LineName`, `Color`) VALUES <{{{><}}}>('Line 1', 'Red'),<{{{><}}}>('Line 2', 'Orange'),<{{{><}}}>('Line 3', 'Green');<{{{><}}}><{{{><}}}>INSERT INTO `Stations` (`StationName`, `LineID`, `Zone`) VALUES <{{{><}}}>('Helwan', 1, 1),<{{{><}}}>('Maadi', 1, 1),<{{{><}}}>('Sadat', 1, 2),<{{{><}}}>('Opera', 2, 2),<{{{><}}}>('Dokki', 2, 2),<{{{><}}}>('Attaba', 3, 2),<{{{><}}}>('Adly Mansour', 3, 3);<{{{><}}}><{{{><}}}>INSERT INTO `Tickets` (`StationID`, `Price`) VALUES <{{{><}}}>(1, 8.00), (1, 8.00), (2, 8.00), <{{{><}}}>(3, 12.00), (4, 12.00), (5, 12.00),<{{{><}}}>(6, 15.00), (7, 15.00), (3, 12.00);<{{{><}}}><{{{><}}}><{{{><}}}>
Servers\Metro_DB\QueryHistory\2<|||>1<|||>2026-05-03 23:10:16|MetroDB|15|CREATE VIEW `DailyReportView` AS<{{{><}}}>SELECT s.`StationName`, l.`LineName`, t.`Price`, t.`PurchaseDate`<{{{><}}}>FROM `Tickets` t<{{{><}}}>JOIN `Stations` s ON t.`StationID` = s.`StationID`<{{{><}}}>JOIN `Lines` l ON s.`LineID` = l.`LineID`;<{{{><}}}><{{{><}}}>
Servers\Metro_DB\QueryHistory\3<|||>1<|||>2026-05-03 23:11:11|MetroDB|0|DELIMITER //<{{{><}}}>CREATE PROCEDURE `SellTicket`(IN s_id INT, IN t_price DECIMAL(10,2))<{{{><}}}>BEGIN<{{{><}}}>    INSERT INTO `Tickets` (`StationID`, `Price`) VALUES (s_id, t_price);<{{{><}}}>END //<{{{><}}}>DELIMITER ;<{{{><}}}><{{{><}}}>
Servers\Metro_DB\QueryHistory\4<|||>1<|||>2026-05-03 23:12:07|metrodb|16|USE metrodb;<{{{><}}}>DELIMITER //<{{{><}}}>CREATE TRIGGER `Before_Station_Delete`<{{{><}}}>BEFORE DELETE ON `Stations`<{{{><}}}>FOR EACH ROW<{{{><}}}>BEGIN<{{{><}}}>    IF (SELECT COUNT(*) FROM `Tickets` WHERE `StationID` = OLD.`StationID`) > 0 THEN<{{{><}}}>        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot delete station with existing tickets';<{{{><}}}>    END IF;<{{{><}}}>END //<{{{><}}}>DELIMITER ;<{{{><}}}><{{{><}}}>
Servers\test\SessionCreated<|||>1<|||>2026-04-22 19:32:18
Servers\test\Host<|||>1<|||>127.0.0.1
Servers\test\WindowsAuth<|||>3<|||>0
Servers\test\CleartextPluginEnabled<|||>3<|||>0
Servers\test\User<|||>1<|||>root
Servers\test\Password<|||>1<|||>7
Servers\test\LoginPrompt<|||>3<|||>0
Servers\test\Port<|||>1<|||>3306
Servers\test\NetType<|||>3<|||>0
Servers\test\Compressed<|||>3<|||>0
Servers\test\LocalTimeZone<|||>3<|||>0
Servers\test\QueryTimeout<|||>3<|||>30
Servers\test\KeepAlive<|||>3<|||>20
Servers\test\FullTableStatus<|||>3<|||>1
Servers\test\Databases<|||>1<|||>
Servers\test\Library<|||>1<|||>libmariadb.dll
Servers\test\Comment<|||>1<|||>
Servers\test\StartupScriptFilename<|||>1<|||>
Servers\test\TreeBackground<|||>3<|||>536870911
Servers\test\SSHtunnelActive<|||>3<|||>0
Servers\test\SshExecutable<|||>1<|||>
Servers\test\SSHtunnelHost<|||>1<|||>
Servers\test\SSHtunnelHostPort<|||>3<|||>22
Servers\test\SSHtunnelUser<|||>1<|||>
Servers\test\SSHtunnelPassword<|||>1<|||>5
Servers\test\SSHtunnelTimeout<|||>3<|||>4
Servers\test\SSHtunnelPrivateKey<|||>1<|||>
Servers\test\SSHtunnelPort<|||>3<|||>3307
Servers\test\SSL_Active<|||>3<|||>0
Servers\test\SSL_Key<|||>1<|||>
Servers\test\SSL_Cert<|||>1<|||>
Servers\test\SSL_CA<|||>1<|||>
Servers\test\SSL_Cipher<|||>1<|||>
Servers\test\SSL_Verification<|||>3<|||>2
Servers\test\IgnoreDatabasePattern<|||>1<|||>
Servers\test\LogFileDdl<|||>3<|||>0
Servers\test\LogFileDml<|||>3<|||>0
Servers\test\LogFilePath<|||>1<|||>C:\Users\FATMA-HASANIN\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\test\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\test\ConnectCount<|||>3<|||>1
Servers\test\ServerVersion<|||>3<|||>80403
Servers\test\LastConnect<|||>1<|||>2026-04-22 19:32:28
Servers\test\QueryHistory\1<|||>1<|||>2026-04-22 21:18:37|Task_1|188|DROP DATABASE  IF EXISTS Task_1;<{{{><}}}>CREATE DATABASE Task_1;<{{{><}}}>USE Task_1;<{{{><}}}><{{{><}}}>CREATE TABLE departments(<{{{><}}}>	Dep_Id INT PRIMARY key,<{{{><}}}>	Dep_Name VARCHAR(255)<{{{><}}}>);<{{{><}}}>CREATE TABLE students(<{{{><}}}>	 Student_Id INT PRIMARY key,<{{{><}}}>	 Student_Name VARCHAR(255),<{{{><}}}>	 Dep_ID INT,<{{{><}}}>	<{{{><}}}>	FOREIGN KEY (Dep_ID) REFERENCES Departments(Dep_ID)<{{{><}}}>);<{{{><}}}>
Servers\test\QueryHistory\2<|||>1<|||>2026-04-23 01:20:21|Task_1|47|DROP PROCEDURE IF EXISTS total  ;<{{{><}}}>DELIMITER &&<{{{><}}}>CREATE PROCEDURE total (OUT total_s INT)<{{{><}}}>BEGIN<{{{><}}}>SELECT COUNT(students.Student_Id) INTO total_s FROM students;<{{{><}}}>END &&<{{{><}}}><{{{><}}}>DELIMITER ;<{{{><}}}>CALL total(@total_s);<{{{><}}}>SELECT @total_s ;
Servers\university_cms\SessionCreated<|||>1<|||>2026-04-06 17:16:04
Servers\university_cms\Host<|||>1<|||>127.0.0.1
Servers\university_cms\WindowsAuth<|||>3<|||>0
Servers\university_cms\CleartextPluginEnabled<|||>3<|||>0
Servers\university_cms\User<|||>1<|||>root
Servers\university_cms\Password<|||>1<|||>6
Servers\university_cms\LoginPrompt<|||>3<|||>0
Servers\university_cms\Port<|||>1<|||>3306
Servers\university_cms\NetType<|||>3<|||>0
Servers\university_cms\Compressed<|||>3<|||>0
Servers\university_cms\LocalTimeZone<|||>3<|||>0
Servers\university_cms\QueryTimeout<|||>3<|||>30
Servers\university_cms\KeepAlive<|||>3<|||>20
Servers\university_cms\FullTableStatus<|||>3<|||>1
Servers\university_cms\Databases<|||>1<|||>
Servers\university_cms\Library<|||>1<|||>libmariadb.dll
Servers\university_cms\Comment<|||>1<|||>
Servers\university_cms\StartupScriptFilename<|||>1<|||>
Servers\university_cms\TreeBackground<|||>3<|||>536870911
Servers\university_cms\SSHtunnelActive<|||>3<|||>0
Servers\university_cms\SshExecutable<|||>1<|||>
Servers\university_cms\SSHtunnelHost<|||>1<|||>
Servers\university_cms\SSHtunnelHostPort<|||>3<|||>22
Servers\university_cms\SSHtunnelUser<|||>1<|||>
Servers\university_cms\SSHtunnelPassword<|||>1<|||>2
Servers\university_cms\SSHtunnelTimeout<|||>3<|||>4
Servers\university_cms\SSHtunnelPrivateKey<|||>1<|||>
Servers\university_cms\SSHtunnelPort<|||>3<|||>3307
Servers\university_cms\SSL_Active<|||>3<|||>0
Servers\university_cms\SSL_Key<|||>1<|||>
Servers\university_cms\SSL_Cert<|||>1<|||>
Servers\university_cms\SSL_CA<|||>1<|||>
Servers\university_cms\SSL_Cipher<|||>1<|||>
Servers\university_cms\SSL_Verification<|||>3<|||>2
Servers\university_cms\IgnoreDatabasePattern<|||>1<|||>
Servers\university_cms\LogFileDdl<|||>3<|||>0
Servers\university_cms\LogFileDml<|||>3<|||>0
Servers\university_cms\LogFilePath<|||>1<|||>C:\Users\FATMA-HASANIN\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\university_cms\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\university_cms\ConnectCount<|||>3<|||>3
Servers\university_cms\ServerVersion<|||>3<|||>80403
Servers\university_cms\LastConnect<|||>1<|||>2026-04-08 12:06:25
Servers\university_cms\lastUsedDB<|||>1<|||>
